services:
  - type: web
    name: luddy-dash-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python dash_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14